#if !canImport(ObjectiveC)
import XCTest

extension SketchXTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SketchXTests = [
        ("testExport", testExport),
        ("testUsage", testUsage),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SketchXTests.__allTests__SketchXTests),
    ]
}
#endif
